[package]
name = "bitrst"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "crates/bitrst-core",
    "crates/bitrst-crypto",
    "crates/bitrst-miner",
]

[features]
test-short-period = ["bitrst-core/test-short-period"]

[dependencies]
bitrst-core = { path = "crates/bitrst-core" }
bitrst-miner = { path = "crates/bitrst-miner" }
clap = { version = "4", features = ["derive"] }
hex = "0.4"
